"""Add column to polls to track if a poll is hidden

Revision ID: 8931fb4f5fc7
Revises: 5459d0ce6fcb
Create Date: 2023-04-24 11:39:14.664267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8931fb4f5fc7"
down_revision = "5459d0ce6fcb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("polls", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hidden", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("polls", schema=None) as batch_op:
        batch_op.drop_column("hidden")

    # ### end Alembic commands ###
