---

on:
  pull_request:
    paths:
      - 'client/**/*.ts'
      - 'client/**/*.tsx'
      - 'client/**/*.js'
      - 'client/**/*.json'
      - 'client/**/*.css'
      - 'client/**/*.svg'
  workflow_dispatch:

jobs:
  quality-checks:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: 'client'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 'Install dependencies'
        run: 'npm ci'

      - name: 'Code formatting'
        run: 'npm run check:format'

      - name: 'Lint'
        run: 'npm run lint'

      - name: 'Build'
        run: 'npm run build'

...
